---

- hosts:  all
  become: true
  tasks:

  - name: install updates (Ubuntu)
    apt:
     upgrade: dist
     update_cache: yes
    when: ansible_distribution == "ubuntu"

  - name: install updates (centOS)
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "centOS"



- hosts: web_servers
  become: true
  tasks:
  
  - name: install apache2 and php  packages
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "ubuntu"


  - name: install apache2 and php packages
    dnf:
      name: 
      - httpd
      - php
      state: latest
    when: ansible_distribution == "CentOS"

