---

- hosts: all
  become: true
  tasks:

   - name: install updates (Ubuntu)
     apt:
     upgrade: dist
     update_cache: yes
  when: ansible_distribution == "ubuntu"

 - name: install updates (centOS)
   dnf:
     update_only: yes
     update_cache: yes
   when: ansible_distribution == "centOS"



 - hosts: web_servers
   become: true
   tasks:
  
 - name: install apache2 and php  packages
   apt:
     name:
        - apache2
        - libapache2-mod-php
     state: latest
   when: ansible_distribution == "ubuntu"


 - name: install apache2 and php packages
   dnf:
     name: 
      - httpd
      - php
     state: latest
   when: ansible_distribution == "CentOS"

  - name: copy default html file for site
    tags: apache,apache2,httpd
    copy: 
      scr: defualt_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644


 
 - hosts: db_server
   become: true
   task:
   
 - name: install mariadb package (centos)
   dnf:
     name: mariadb
     state: latest
   when: ansible_distribution == "centos"

 - name: install mariadb package (ubuntu)
   apt:
     name: mariadb-server
     state: latest
   when: ansible_distribution == "ubuntu"
